# fly.toml file generated for amis-fabric-database on 2022-09-09T15:40:52-05:00

app = "amis-fabric-database"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]  
  HOST = "amis-fabric-database.fly.dev"
  PORT = "8080"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "1"
  RAILS_SERVE_STATIC_FILES = "1"
  SCOPES = "read_products,read_files,write_files,read_product_listings"
  SHOPIFY_API_KEY = "2f99200ced7270ebbb09324c3e6abab4"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
